version: '3.4'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"

  etlservice:
    image: ${DOCKER_REGISTRY}etlservice
    build:
      context: .
      dockerfile: ETLService/Dockerfile
    links:
      - "postgres"
    depends_on:
      - "postgres"
    ports:
      - "35000:80"
    # Registry
    volumes:
       - registry-data:/app/Registry
volumes:
  - registry-data: